# Code generated by SdkContractGenerator. DO NOT EDIT.

CONTRACT = {
    "edit-image": {
        "models": ["gpt-image-1.5"],
        "fields_by_model": {
            "gpt-image-1.5": {
                "aspect_ratio": {
                    "enum": ["1:1", "2:3", "3:2"],
                    "required": True
                },
                "prompt": {
                    "required": True
                },
                "quality": {
                    "enum": ["medium", "high"],
                    "required": True
                },
                "source_image_urls": {
                    "required": True
                }
            }
        }
    },
    "text-to-image": {
        "models": ["gpt-image-1.5"],
        "fields_by_model": {
            "gpt-image-1.5": {
                "aspect_ratio": {
                    "enum": ["1:1", "2:3", "3:2"],
                    "required": True
                },
                "prompt": {
                    "required": True
                },
                "quality": {
                    "enum": ["medium", "high"],
                    "required": True
                }
            }
        }
    }
}
